import numpy as np
import struct
import wave
import matplotlib.pyplot as plt


frame_rate = 48000.0 #Audio frame rate

infile = "sine_test.wav" # Sine wav generated by sine_wave.py

num_samples = 48000 #Number of samples

wav_file = wave.open(infile, 'r')  #reads(opens) the file (infile)

data = wav_file.readframes(num_samples) #Reads and returns at most n frames of audio, as a bytes object.
wav_file.close()

#Unpacks the audio file and converts it from hex to bytes
data = struct.unpack('{n}h'.format(n = num_samples),data)

#convert data to numpy array (matrix)
data = np.array(data)

data_fft = np.fft.fft(data) #taking the Fast fourier transform of the data
freq = np.abs(data_fft) # converts to real components


#Plot the sine wave and the harmonics present in it
plt.subplots_adjust(hspace=.8)
plt.subplot(2,1,1)
plt.plot(data[:400])
plt.title("Original audio wave")
 
plt.subplot(2,1,2)
plt.plot(freq)
plt.title("Frequencies found")
plt.xlim(0,1200)
plt.show()